// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFPP8IafCjkVUkAGysGbnLqrRS-2AL-Y',
    appId: '1:572088191006:android:c87feb0be04f774cc6c60f',
    messagingSenderId: '572088191006',
    projectId: 'e-commerce-pos',
    storageBucket: 'e-commerce-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nWL7FeloTBgpcxxibWj2wxxgsZsuMUc',
    appId: '1:572088191006:ios:9f2fdeb11d072e23c6c60f',
    messagingSenderId: '572088191006',
    projectId: 'e-commerce-pos',
    storageBucket: 'e-commerce-pos.appspot.com',
    androidClientId: '572088191006-faand1f71ddl1p9u6l22t7l7t7ud1a9u.apps.googleusercontent.com',
    iosClientId: '572088191006-8298l7im0cfhbou7gfjt4v8r3lnhf3au.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerce',
  );
}
